name: Pull docker image (same repo)
on: push

permissions:
 packages: write

jobs:
 all:
  runs-on: ubuntu-latest
  
  steps:
   - name: Login to GitHub container Registry
     run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
   - name: List the image 
     run: docker image ls
   - name: Pull the image from the registry
     run: docker pull ghcr.io/aashij-testorg/monica:apache
   - name: List the image 
     run: docker image ls | grep monica
