name: Docker Push container at ORG level
on: push

permissions:
 packages: write

jobs:
 all:
  runs-on: ubuntu-latest
  
  steps:
   - name: Login to GitHub container Registry
     run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
   - name: Build the Docker image
     run: docker pull monica:latest
   - name: Tag the Docker image
     run: docker tag monica:latest ghcr.io/aashij-testorg/monica:latest
   - name: Push the Docker image to the registry
     run: docker push ghcr.io/aashij-testorg/monica:latest
